### ISSUE TITLE
 Album Cover  for each song

### ISSUE THREAD

**Issue by ronaldG19** [Kwasow/flutter_audio_as_service#4]
I wonder how can I change the Album cover for each song played!

**Comment by Kwasow** [comment]
As of now it's only possible to select a cover from the drawable folder, but I hope to find a way to load them from the internet.

**Comment by Kwasow** [comment]
TODO:
1. Load image from online url ✔️
2. Load image from path
3. Add the ability to set a fallback offline image (from drawables)

**Comment by Kwasow** [comment]
This feature has been fully added and tested in commit 7b5d9c5
